Add new features registration user
MasDev-12/CryptoBank.WebApi pull request #1
Opened 2023-06-11 06:06 UTC by MukanMasud1992

Add new features register user

2023-06-14 05:11 UTC, mitro requested changes

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Domain/Role.cs
> +    public virtual User User { get; set; }
Можно на использовать `virtual` в доменных сущностях. Это нужно для lazy loading, которое лучше не использовать. И в `User` тоже убери

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Registration/UsersBuilderExtensions.cs
> +        builder.Services.Configure<PasswordHashingOptions>(builder.Configuration.GetSection("Features:PasswordHashingOptions"));
`PasswordHashingOptions` это не фича. Можно просто на корневую секцию "PasswordHashing" замапить. Суффикс Options не стоит использовать в имени секции. И так понятно, что это опции

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +[Route("/user")]
`/users`

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        _mediator=mediator;
Пробелы вокруг `=`

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        byte[] salt = new byte[32];
Размер соли в байтах стоит в опции вынести

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            byte[] passwordHash = argon2.GetBytes(32);
Размера хеша в байтах стоит в опции вынести

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            return (Convert.ToBase64String(passwordHash));
Ненужные скобки вокруг `Convert`

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        using var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password))
`using` можно без скобок использовать. В методе `GenerateSalt` ты это уже делаешь

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            && user.Iterations == _options.Iterations)
Можно упростить:

```
return _options.MemorySize
    && user.Parallelism ==_options.Parallelism
    && user.Iterations == _options.Iterations;
```

И вообще, метод не нужен и не используется - стоит удалить

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        _options=options.Value;
Опять проблема с пробелами

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +    protected override void OnModelCreating(ModelBuilder modelBuilder)
Тут у тебя свойства находятся над конструктором, а в классе `User` под конструктором. Нужно выбрать один подход и его придерживаться. И нужно отделять свойства от конструктора пустой строкой

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +          .IsRequired();
Уехало форматирование

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +              .IsRequired();
Уехало форматирование

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +            .IsRequired();
Тут и ниже проблема с форматированием

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +
Ненужная пустая строка

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            _passwordHeshingService=passwordHeshingService;
Проблема с пробелами

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            var passwordSalt = _passwordHeshingService.GenerateSalt();
Не стоит делать публичный метод для получения соли. Сделай его приватным и просто внутри `_passwordHeshingService.GetPasswordHash` вызови. Код сразу упросится. Хендлеру неважно, что за соль используется - это всё заботы `PasswordHashingService`

2023-06-14 05:11 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            if (request.Email.Equals(_usersOptions.AdministratorEmail))
Нужно сравнивать имейлы после приведения к нижнему регистру. Если у тебя в опциях будет admin@cryptobank.com, а в запросе придёт Admin@CryptoBank.com, то проверка не пройдет. Хотя это одинаковые имейлы. И при создании пользователя тоже нужно `ToLower()` использовать

2023-06-14 17:46 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Domain/Role.cs
> +    public virtual User User { get; set; }
> Можно на использовать `virtual` в доменных сущностях. Это нужно для lazy loading, которое лучше не использовать. И в `User` тоже убери

` public User()
    {
        Roles = new HashSet<Role>();
    }
    public long Id { get; set; }
    public string Email { get; set; }
    public string PasswordHashAndSalt { get; set; }
    public int MemorySize { get; set; }
    public int Iterations { get; set; }
    public int Parallelism { get; set; }
    public DateTime BirthDate { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public ICollection<Role> Roles { get; set; }` Исправлено

`public class Role
{
    public long Id { get; set; }
    public UserRole Name { get; set; }
    public long UserId { get; set; }
    public DateTime CreatedAt { get; set; }
    public User User { get; set; }
}` Исправлено

2023-06-14 17:46 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Registration/UsersBuilderExtensions.cs
> +        builder.Services.Configure<PasswordHashingOptions>(builder.Configuration.GetSection("Features:PasswordHashingOptions"));
> `PasswordHashingOptions` это не фича. Можно просто на корневую секцию "PasswordHashing" замапить. Суффикс Options не стоит использовать в имени секции. И так понятно, что это опции

`public class PasswordHashingOptions
{
    public int MemorySize { get; set; }
    public int Iterations { get; set; }
    public int Parallelism { get; set; }
    public int HashLengthInBytes { get; set; }
}
` Исправлено

`"Argon2Config": {
    "MemorySize": 64,
    "Iterations": 10,
    "Parallelism": 8,
    "HashLengthInBytes": 32
  }`
Исправлено

2023-06-14 17:47 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +[Route("/user")]
> `/users`
`[ApiController]
[Route("/users")]`
Исправлено

2023-06-14 17:47 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        _mediator=mediator;
> Пробелы вокруг `=`
`public UserController(IMediator mediator)
    {
        _mediator = mediator;
    }
` Исправлено

2023-06-14 17:48 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        byte[] salt = new byte[32];
> Размер соли в байтах стоит в опции вынести

`public class PasswordHashingOptions
{
    public int MemorySize { get; set; }
    public int Iterations { get; set; }
    public int Parallelism { get; set; }
    public int HashLengthInBytes { get; set; }
}`

`builder.Services.Configure<PasswordHashingOptions>(builder.Configuration.GetSection("Argon2Config"));`

`"Argon2Config": {
    "MemorySize": 64,
    "Iterations": 10,
    "Parallelism": 8,
    "HashLengthInBytes": 32
  }`

Исправлено

2023-06-14 17:49 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            byte[] passwordHash = argon2.GetBytes(32);
Исправлено

2023-06-14 17:50 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            return (Convert.ToBase64String(passwordHash));
Исправлено

2023-06-14 17:51 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        using var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password))
Исправлено
` byte[] passwordSalt = GenerateSalt();
        using var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password))
        {
            DegreeOfParallelism = _options.Parallelism,
            MemorySize = _options.MemorySize,
            Iterations = _options.Iterations,
            Salt = passwordSalt
        };
        byte[] passwordHash = argon2.GetBytes(_options.HashLengthInBytes);
        var passwordHashAndSalt = $"{Convert.ToBase64String(passwordHash)}:{Convert.ToBase64String(passwordSalt)}";
        return passwordHashAndSalt;`

2023-06-14 17:52 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +            && user.Iterations == _options.Iterations)
Придерживаюсь принципа YAGNI осталось с черновика, случайно добавил

> Можно упростить:
> 
> ```
> return _options.MemorySize
>     && user.Parallelism ==_options.Parallelism
>     && user.Iterations == _options.Iterations;
> ```
> 
> И вообще, метод не нужен и не используется - стоит удалить

2023-06-14 17:52 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Users/Services/PasswordHashingService.cs
> +        _options=options.Value;
> Опять проблема с пробелами

`   public PasswordHashingService(IOptions<PasswordHashingOptions> options)
    {
        _options = options.Value;
    }`
исправлено

2023-06-14 17:54 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +    protected override void OnModelCreating(ModelBuilder modelBuilder)
`    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        MapUsers(modelBuilder);
        MapRoles(modelBuilder);
    }

    public DbSet<User> Users { get; set; }
    public DbSet<Role> Roles { get; set; }`
Исправлено

2023-06-14 17:54 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +          .IsRequired();
> Уехало форматирование

Исправлено

2023-06-14 17:54 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +              .IsRequired();
> Уехало форматирование

Исправлено

2023-06-14 17:54 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +            .IsRequired();
> Тут и ниже проблема с форматированием

Исправлено

2023-06-14 17:54 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +
> Ненужная пустая строка

Исправлено

2023-06-14 17:55 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            _passwordHeshingService=passwordHeshingService;
> Проблема с пробелами

`  _applicationDbContext = applicationDbContext;
            _passwordHeshingService = passwordHeshingService;
            _usersOptions = usersOptions.Value;
            _passwordHashOptions = passwordHashOptions.Value;`
Исправлено

2023-06-14 17:56 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            var passwordSalt = _passwordHeshingService.GenerateSalt();
> Не стоит делать публичный метод для получения соли. Сделай его приватным и просто внутри `_passwordHeshingService.GetPasswordHash` вызови. Код сразу упросится. Хендлеру неважно, что за соль используется - это всё заботы `PasswordHashingService`

`private byte[] GenerateSalt()
    {
        byte[] salt = new byte[_options.HashLengthInBytes];
        using var rng = RandomNumberGenerator.Create();
        rng.GetBytes(salt);
        return salt;
    }

    public string GetPasswordHash(string password)
    {
        byte[] passwordSalt = GenerateSalt();
        using var argon2 = new Argon2id(Encoding.UTF8.GetBytes(password))
        {
            DegreeOfParallelism = _options.Parallelism,
            MemorySize = _options.MemorySize,
            Iterations = _options.Iterations,
            Salt = passwordSalt
        };
        byte[] passwordHash = argon2.GetBytes(_options.HashLengthInBytes);
        var passwordHashAndSalt = $"{Convert.ToBase64String(passwordHash)}:{Convert.ToBase64String(passwordSalt)}";
        return passwordHashAndSalt;
    }`
` UserRole userRole = UserRole.UserRole;
            var passwordHashAndSalt = _passwordHeshingService.GetPasswordHash(request.Password);
            if (request.Email.Equals(_usersOptions.AdministratorEmail.ToLower()))
            {
                userRole = UserRole.AdministratorRole;
            }
            var user = new User()
            {
                Email = request.Email.ToLower(),
                PasswordHashAndSalt = passwordHashAndSalt,`

Исправлено

2023-06-14 17:56 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +            if (request.Email.Equals(_usersOptions.AdministratorEmail))
> Нужно сравнивать имейлы после приведения к нижнему регистру. Если у тебя в опциях будет [admin@cryptobank.com](mailto:admin@cryptobank.com), а в запросе придёт [Admin@CryptoBank.com](mailto:Admin@CryptoBank.com), то проверка не пройдет. Хотя это одинаковые имейлы. И при создании пользователя тоже нужно `ToLower()` использовать

`if (request.Email.Equals(_usersOptions.AdministratorEmail.ToLower()))`
` var user = new User()
            {
                Email = request.Email.ToLower(),`

Исправлено

2023-06-15 14:27 UTC, mitro approved these changes

2023-06-16 05:00 UTC, merged