add new features/tests-features-accounts
MasDev-12/CryptoBank.WebApi pull request #10
Opened 2023-07-14 15:34 UTC by MukanMasud1992

Add new features/tests-features-accounts please check!
Thank you

2023-07-17 15:42 UTC, mitro requested changes

2023-07-17 15:42 UTC, mitro commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/CreateAccountsTests.cs
> +    public async Task Should_return_LogicConflictException()
Нужно еще написать сценарий, когда должна вернуться ошибка. Типа `Should_return_LogicConflict_when_accounts_limit_exceeded`

2023-07-17 15:42 UTC, mitro commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/CreateAccountsTests.cs
> +    public async Task Should_exist_account()
`Should_validate_user_exists`. Ты так называл подобные тесты в других файлах. Нужно чтобы имена были согласованы

2023-07-17 15:42 UTC, mitro commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/GetAccountsByPeriodTests.cs
> +        var accounts = new List<Account>();
Если проверяешь, что не пройдет аутентификация, все эти подготовки можно не делать. Всё равно до них код не дойдет

2023-07-17 15:42 UTC, mitro commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/GetAccountsByPeriodTests.cs
> +        var accounts = new List<Account>();
Тут можно всю эту подготовку не делать. Всё равно выполнение досюда не дойдет. А чем меньше кода, тем проще понимать, что тест проверяет

2023-07-18 03:33 UTC, MukanMasud1992 commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/CreateAccountsTests.cs
> +    public async Task Should_return_LogicConflictException()
> Нужно еще написать сценарий, когда должна вернуться ошибка. Типа `Should_return_LogicConflict_when_accounts_limit_exceeded`

Исправлено

2023-07-18 03:33 UTC, MukanMasud1992 commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/CreateAccountsTests.cs
> +    public async Task Should_exist_account()
> 

Исправлено

2023-07-18 03:34 UTC, MukanMasud1992 commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/GetAccountsByPeriodTests.cs
> +        var accounts = new List<Account>();
> Если проверяешь, что не пройдет аутентификация, все эти подготовки можно не делать. Всё равно до них код не дойдет

Исправлено

2023-07-18 03:37 UTC, MukanMasud1992 commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/GetAccountsByPeriodTests.cs
> +        var accounts = new List<Account>();
> Тут можно всю эту подготовку не делать. Всё равно выполнение досюда не дойдет. А чем меньше кода, тем проще понимать, что тест проверяет

а тут думаю, нужно, т.к. я проверяю правильность роли у пользователя. Роль должна быть аналитиком, я же юзаю роль обычного пользователя

2023-07-18 03:38 UTC, MukanMasud1992 commented on CryptoBank.WebApi.Integrations.Tests/Features/Accounts/GetAccountsByPeriodTests.cs
> +        var accounts = new List<Account>();
> Тут можно всю эту подготовку не делать. Всё равно выполнение досюда не дойдет. А чем меньше кода, тем проще понимать, что тест проверяет

Переименовал метод `Should_get_response_forbidden_when_role_wrong`

2023-07-19 06:18 UTC, mitro approved these changes

2023-07-19 08:50 UTC, merged