Add new features/auth
MasDev-12/CryptoBank.WebApi pull request #2
Opened 2023-06-16 05:47 UTC by MukanMasud1992

Add new Features/auth with accessToken please check

2023-06-16 14:15 UTC, mitro requested changes

2023-06-16 14:15 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()),
Пробел после запятой нужен. И ниже тоже

2023-06-16 14:15 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +        public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
Не хватает пустой строки

2023-06-16 14:15 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +            if (!(user.MemorySize == _passwordHasherOptions.MemorySize
Это нужно делать после того, как ты убедился, что в запросе пришел верный пароль. Иначе у тебя юзер сможет залогиниться с любым паролем в этом случае. Потому что ты пришедший пароль сохраняешь в `user.PasswordHashAndSalt`, а потом сравниваешь его с хешем того же самого пароля. Естественно они совпадут.

И еще важный момент. Чтобы всё это работало, тебе нужно пришедший пароль хешировать не с теми параметрами, что в конфиге, а с теми, что у тебя сохранены в пользователе. То есть в PasswordHashingService прокинуть параметры из юзера

2023-06-16 14:15 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +            if (passwordHashAndSalt != user.PasswordHashAndSalt)
Тут лучше просто хеш пришедшего пароля сравнивать с паролем из `parts[0]`

2023-06-17 09:00 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()),
> Пробел после запятой нужен. И ниже тоже

`   var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Email, user.Email),
            };
`
Исправлено

2023-06-17 09:00 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +        public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
> Не хватает пустой строки

`      _passwordHasherOptions = passwordHasherOptions.Value;
        }

        public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
        {
`
Исравлено

2023-06-17 09:05 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +            if (!(user.MemorySize == _passwordHasherOptions.MemorySize
> Это нужно делать после того, как ты убедился, что в запросе пришел верный пароль. Иначе у тебя юзер сможет залогиниться с любым паролем в этом случае. Потому что ты пришедший пароль сохраняешь в `user.PasswordHashAndSalt`, а потом сравниваешь его с хешем того же самого пароля. Естественно они совпадут.
> 
> И еще важный момент. Чтобы всё это работало, тебе нужно пришедший пароль хешировать не с теми параметрами, что в конфиге, а с теми, что у тебя сохранены в пользователе. То есть в PasswordHashingService прокинуть параметры из юзера

Проработал, понял, что при смене конфигурации хеширования я просто перезаписываю новый пароль, тем самым, любой пароль станет правильным, изменил алгоритм, сначала проверка пароля с конфигами user из db, потом сравнение auth конфигов из db, с конфигами приложения в файле конфигурации, и только после этого в случае разницы перезаписываю пароль и новые конфиг.данные

2023-06-19 16:07 UTC, mitro approved these changes

2023-06-20 04:27 UTC, merged