Add new features/get-user-info
MasDev-12/CryptoBank.WebApi pull request #3
Opened 2023-06-20 05:02 UTC by MukanMasud1992

Add new features/get-user-info

2023-06-21 05:38 UTC, mitro requested changes

2023-06-21 05:38 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    [HttpGet("get-user-info")]
Можно просто `info`, из предыдущего пути `users` и так понятно, что речь идет о юзере

2023-06-21 05:38 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        long userId = Convert.ToInt64(user.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value);
Тут нужно использовать `SingleOrDefault`. Тем самым ты в коде обозначишь, что ожидаешь только один клейм такого типа

2023-06-21 05:38 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        long userId = Convert.ToInt64(user.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value);
Что произойдёт, если у тебя в юзере не будет клейма с таким типом? Или будет, но внутри него будет не число, а какой-нибудь текст? Какое исключение в этом случае ты получишь?

2023-06-21 05:38 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/GetUserInfo.cs
> +            var user = await _applicationDbContext.Users.Include(u => u.Roles).FirstAsync(u => u.Id == request.UserId, cancellationToken);
Нужно использовать `SingleAsync`, чтобы дать понять, что в БД ожидается только один пользователь с таким идентификатором. А он может быть только один, потому что `Id` это первичный ключ

2023-06-21 14:07 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        long userId = Convert.ToInt64(user.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value);
> Тут нужно использовать `SingleOrDefault`. Тем самым ты в коде обозначишь, что ожидаешь только один клейм такого типа

Разницу понял, да и понимал в принципе, по невнимательности оставил First, вместо Single, но перечитал доки, закрепил. Рахмет!Исправлено

2023-06-21 14:07 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +    [HttpGet("get-user-info")]
> Можно просто `info`, из предыдущего пути `users` и так понятно, что речь идет о юзере

Исправил

2023-06-21 14:08 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/GetUserInfo.cs
> +            var user = await _applicationDbContext.Users.Include(u => u.Roles).FirstAsync(u => u.Id == request.UserId, cancellationToken);
> Нужно использовать `SingleAsync`, чтобы дать понять, что в БД ожидается только один пользователь с таким идентификатором. А он может быть только один, потому что `Id` это первичный ключ
Исправлено

2023-06-21 14:08 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        long userId = Convert.ToInt64(user.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value);
> Что произойдёт, если у тебя в юзере не будет клейма с таким типом? Или будет, но внутри него будет не число, а какой-нибудь текст? Какое исключение в этом случае ты получишь?

Исправлено

2023-06-22 04:05 UTC, mitro approved these changes

2023-06-22 13:03 UTC, merged