Features/accounts
MasDev-12/CryptoBank.WebApi pull request #5
Opened 2023-06-23 16:59 UTC by MukanMasud1992

Add new features/accounts

>create
>get-info
>get-info-by period

please check

2023-06-27 03:20 UTC, mitro requested changes

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    [HttpPost("create")]
Можно просто `[HttpPost]` без пути. POST /accounts и так значит, что это создание аккаунта

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +        var user = HttpContext?.User;
Нарушение DRY. Нужно вынести в какой-нибудь хелпер и использовать его вместо дублирования этого кода по экшенам. И сам код пересмотри. Ты там можешь `NullReferenceException` поймать. Нужно поправить

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<CreateAccount.Response> CreateAccount(CreateAccount.Request request, CancellationToken cancellationToken)
Тут лучше отдельную модельку завести, чтобы там не было `UserId`. Иначе это вводит в заблуждение. Тем более ты этот объект не закидываешь в медиатор, а просто из него свойства извлекаешь

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    [HttpGet("get-info")]
"get-info" кажется, что ты инфу по одному аккаунту хочешь получить. Тут лучше что-то типа "own". GET /accounts/own

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<GetAccountsByPeriod.Response> GetAccountsByPeriod([FromBody] GetAccountsByPeriod.Request request, CancellationToken cancellationToken)
Body не используется в GET запросах. Нужно поправить на `[FromQuery]`

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +                    var userExists = await applicationDbContext.Users.AnyAsync(user => user.Id == x);
Опять не передаешь `token`. И ниже тоже

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +            if (accounts > _options.MaxAccountsPerUser)
Тут логическая ошибка. Если `accounts` вернётся равным `5`, то эта проверка у тебя пройдет. И в итоге юзер создаст шестой аккаунт, что недопустимо. Поправь проверку

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/GetOwnAccounts.cs
> +            List<AccountModel> accountModels = accounts?.Select(account => new AccountModel()
Лучше `Select` делать до `ToListAsync`, чтобы проекция была выполнена в базе и в SQL-запросе 'SELECT ...' были указаны только нужные тебе поля https://itnext.io/optimising-entity-framework-core-queries-using-projection-14063ea23f97

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/GetOwnAccounts.cs
> +    }
`ToList` никогда не может вернуть `null`, поэтому `?? new List<AccountModel>()` тут лишнее

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/GetAccountsByPeriod.cs
> +            return start<end;
Пробелы

2023-06-27 03:20 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/GetAccountsByPeriod.cs
> +        private async Task<bool> IsValidRange(DateOnly start, DateOnly end, CancellationToken cancellationToken)
Этот метод не производит никаких асинхронных операций. Сделай его синхронным

2023-06-27 05:58 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<CreateAccount.Response> CreateAccount(CreateAccount.Request request, CancellationToken cancellationToken)
> Тут лучше отдельную модельку завести, чтобы там не было `UserId`. Иначе это вводит в заблуждение. Тем более ты этот объект не закидываешь в медиатор, а просто из него свойства извлекаешь

Я же userId использую для создания и привязки аккаунта, он нужен я его в медиаторе как раз передаю, чтобы и проверки совершить по кол-ву аккаунтов, думаю тут даже модель не нужна

2023-06-28 04:58 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<CreateAccount.Response> CreateAccount(CreateAccount.Request request, CancellationToken cancellationToken)
Да, тебе нужен `UserId` в хендлере запроса. Но в HTTP API его же не должно быть? То есть POST запрос будет выглядеть так:

```
POST /accounts
{
    "currency": "BTC"
}
```

`userId` там нет. А твоей текущей модельке, которая передается в экшен, это поле есть, хотя оно и не нужно. Поэтому можно завести класс `CreateAccountModel` с одним свойством `string Currency` и его использовать в экшене

2023-06-28 04:59 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Helpers/GetUserIdFromClaims.cs
> +        catch (Exception)
Зачем тут эта конструкция? Она бессмысленна по своей сути. Ловишь исключение, чтобы тут же его переотправить

2023-06-28 05:00 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Helpers/GetUserIdFromClaims.cs
> +public static class GetUserIdFromClaims
У тебя этот хелпер используется во всех фичах, а лежит в папке `Accounts`. Стоит в корень проекта вынести

2023-06-28 05:01 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        catch (Exception)
Тоже бессмысленная конструкция

2023-06-28 05:02 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +                    var userExists = await applicationDbContext.Users.AnyAsync(user => user.Id == x);
Ниже не поправил

2023-06-28 05:04 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +                    var accountCount = await applicationDbContext.Accounts.Where(a => a.UserId == x).CountAsync(token);
Стоит эту логику опять вернуть в хендлер. Это не ошибка валидация, это конфликт логики. Юзер всё правильно делает, но просто внутренние правила системы вступают в противоречие с его действиями

2023-06-28 05:05 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +        public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
Пустая строка

2023-06-28 13:12 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<CreateAccount.Response> CreateAccount(CreateAccount.Request request, CancellationToken cancellationToken)
Отработано

> Да, тебе нужен `UserId` в хендлере запроса. Но в HTTP API его же не должно быть? То есть POST запрос будет выглядеть так:
> 
> ```
> POST /accounts
> {
>     "currency": "BTC"
> }
> ```
> 
> `userId` там нет. А твоей текущей модельке, которая передается в экшен, это поле есть, хотя оно и не нужно. Поэтому можно завести класс `CreateAccountModel` с одним свойством `string Currency` и его использовать в экшене

Отработано

2023-06-28 13:13 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +                    var userExists = await applicationDbContext.Users.AnyAsync(user => user.Id == x);
> Опять не передаешь `token`. И ниже тоже

Исправлено

2023-06-28 13:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    [HttpPost("create")]
> Можно просто `[HttpPost]` без пути. POST /accounts и так значит, что это создание аккаунта
Отработано

2023-06-28 13:18 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +        var user = HttpContext?.User;
> Нарушение DRY. Нужно вынести в какой-нибудь хелпер и использовать его вместо дублирования этого кода по экшенам. И сам код пересмотри. Ты там можешь `NullReferenceException` поймать. Нужно поправить


Отработано

2023-06-28 13:18 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    [HttpGet("get-info")]
> "get-info" кажется, что ты инфу по одному аккаунту хочешь получить. Тут лучше что-то типа "own". GET /accounts/own

Отработано

2023-06-28 13:18 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/Contollers/AccountController.cs
> +    public async Task<GetAccountsByPeriod.Response> GetAccountsByPeriod([FromBody] GetAccountsByPeriod.Request request, CancellationToken cancellationToken)
> Body не используется в GET запросах. Нужно поправить на `[FromQuery]`

Отработано

2023-06-28 13:19 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/GetOwnAccounts.cs
> +            List<AccountModel> accountModels = accounts?.Select(account => new AccountModel()
> Лучше `Select` делать до `ToListAsync`, чтобы проекция была выполнена в базе и в SQL-запросе 'SELECT ...' были указаны только нужные тебе поля https://itnext.io/optimising-entity-framework-core-queries-using-projection-14063ea23f97

Исправлено

2023-06-28 13:27 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Helpers/GetUserIdFromClaims.cs
> +        catch (Exception)
> Зачем тут эта конструкция? Она бессмысленна по своей сути. Ловишь исключение, чтобы тут же его переотправить

все тут понял, чуть тормозить начал, в error handler когда feature буду делать, тоже туда ошибку по типу какому-нибудь определю

2023-06-28 13:28 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Accounts/Helpers/GetUserIdFromClaims.cs
> +public static class GetUserIdFromClaims
> У тебя этот хелпер используется во всех фичах, а лежит в папке `Accounts`. Стоит в корень проекта вынести

Исправлено

2023-06-28 13:31 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Users/Requests/Controllers/UserController.cs
> +        catch (Exception)
> Тоже бессмысленная конструкция

Исправлено

2023-06-28 13:38 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +                    var accountCount = await applicationDbContext.Accounts.Where(a => a.UserId == x).CountAsync(token);
> Стоит эту логику опять вернуть в хендлер. Это не ошибка валидация, это конфликт логики. Юзер всё правильно делает, но просто внутренние правила системы вступают в противоречие с его действиями

Исправлено, да это ошибка не валидаци, а ошибка логики приложения

2023-06-28 13:38 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Accounts/Requests/CreateAccount.cs
> +        public async Task<Response> Handle(Request request, CancellationToken cancellationToken)
> Пустая строка

Исправлено

2023-06-28 16:08 UTC, mitro approved these changes

2023-06-29 04:00 UTC, merged