Add new features/refresh-token
MasDev-12/CryptoBank.WebApi pull request #6
Opened 2023-06-29 05:35 UTC by MukanMasud1992

Add new features refresh token

please check

2023-06-30 08:04 UTC, mitro requested changes

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Domain/RefreshToken.cs
> +    public long userId { get; set; }
`UserId`

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Domain/RefreshToken.cs
> +    public bool Revoke { get; set; }
`Revoked`, чтобы было верно с точки зрения английского языка. Не "Отзывать", а "Отозван"

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +          .IsRequired()
Поехали отступы по всему методу

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +            .OnDelete(DeleteBehavior.ClientSetNull);
Думаю, рефреш токены стоит удалять, если удаляется пользователь

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        });
Ты в `GetNewTokens` осуществляешь поиск токена по свойству `Token`. Чтобы это работало быстро, когда будет много токенов, на `Token` нужно создать индекс. Причем это должен быть уникальный индекс

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +            var (AccessToken, RefreshToken) = await _tokenGenerateService.GenerateTokens(user, cancellationToken);
Переменные должны быть с маленькой буквы: `accessToken`, `refreshToken`

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +    private string GenerateAccesToken(User user)
Опечатка в `Access`

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Options/RefreshTokenOptions.cs
> +    public int HashLengthInBytes { get; set; }
Hash ты в логике нигде не используешь. Поэтому нужно переименовать свойство

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var NotRevokeRefreshToken = refreshTokens.FirstOrDefault(t => !t.Revoke);
Нужно с маленькой буквы

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
Пробелы

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                await transaction.RollbackAsync(cancellationToken);
Нужно после этого еще `throw` добавить, чтобы исключение дальше летело. Иначе ты в БД ничего не сохранил, а токены вернул клиенту и он думает, что они валидные

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/GetNewTokens.cs
> +                    .FirstOrDefaultAsync(cancellationToken);
`SingleOrDefaultAsync`. У тебя по семантике может быть 0 или 1 такой токен

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/Controllers/AuthController.cs
> +        var refreshToken = Request.Cookies["refreshToken"];
Строка "refreshToken" в двух местах используется. Нужно вынести в константу

2023-06-30 08:04 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
Если ты будешь удалять токены сразу по истечении срока годности, то ты не сможешь детектить токены, которые украли раньше. Тебе пришлют токен двухдневной давности и его уже не будет в БД. В итоге ты не отзовешь текущий токен. Стоит завести еще одну опцию - сколько хранить рефреш токены. И по истечении этого срока только удалять. Можно с неделю поставить. Тогда если у тебя за эту неделю кто-то украст токен, ты всегда сможешь это определить

2023-06-30 09:42 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        });
> Ты в `GetNewTokens` осуществляешь поиск токена по свойству `Token`. Чтобы это работало быстро, когда будет много токенов, на `Token` нужно создать индекс. Причем это должен быть уникальный индекс

Я получается добавляю в applicationDbContext 
`refreshToken.HasIndex(r => r.Token) // Добавление индекса на свойство Token
            .IsUnique();`
делаю update-db, и также потом в efcore использую поиск, по свойству token, но уже оптимизированный поиск, правильный ход мыслей?

2023-06-30 11:06 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
> Если ты будешь удалять токены сразу по истечении срока годности, то ты не сможешь детектить токены, которые украли раньше. Тебе пришлют токен двухдневной давности и его уже не будет в БД. В итоге ты не отзовешь текущий токен. Стоит завести еще одну опцию - сколько хранить рефреш токены. И по истечении этого срока только удалять. Можно с неделю поставить. Тогда если у тебя за эту неделю кто-то украст токен, ты всегда сможешь это определить

Если я правильно понял, то у меня в сущности RefreshToken, будет еще односвойство TokenExpirePeriod - значение которое я тяну с app.config, условно (168:00:00), и делаю проверку `var overdueTokens = refreshTokens.Where(x => x. TokenExpirePeriod <=DateTime.Now.ToUniversalTime()).ToArray();` и только эти токены я remove делаю.

2023-06-30 11:08 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
> Если ты будешь удалять токены сразу по истечении срока годности, то ты не сможешь детектить токены, которые украли раньше. Тебе пришлют токен двухдневной давности и его уже не будет в БД. В итоге ты не отзовешь текущий токен. Стоит завести еще одну опцию - сколько хранить рефреш токены. И по истечении этого срока только удалять. Можно с неделю поставить. Тогда если у тебя за эту неделю кто-то украст токен, ты всегда сможешь это определить

А если же увеличить свойство ExpiryDate до 168:00:00 то высока вероятность, что токен, могу украсть.

2023-07-03 06:33 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        });
Да, примерно так. Добавляешь `refreshToken.HasIndex(r => r.Token).IsUnique();`, потом добавляешь новую миграцию `dotnet ef migrations add AddRefreshTokenIndexOnToken` и потом можно БД обновить.

После этого в БД создастся новый индекс и запрос по этому полю будет сильно быстрее выполняться

2023-07-03 06:35 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
Да, правильно. В токен ты просаживаешь время, после которого его можно удалять.

> А если же увеличить свойство ExpiryDate до 168:00:00 то высока вероятность, что токен, могу украсть.

Правильно. Поэтому нужно два отдельных свойства:

- время жизни токена
- время, после которого токен можно удалить

2023-07-03 09:14 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Domain/RefreshToken.cs
> +    public long userId { get; set; }
> `UserId`

Исправлено

2023-07-03 09:15 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Domain/RefreshToken.cs
> +    public bool Revoke { get; set; }
> `Revoked`, чтобы было верно с точки зрения английского языка. Не "Отзывать", а "Отозван"

Исправлено

2023-07-03 09:15 UTC, MasDev-12 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +          .IsRequired()
> Поехали отступы по всему методу

Исправлено

2023-07-03 09:15 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +            .OnDelete(DeleteBehavior.ClientSetNull);
> Думаю, рефреш токены стоит удалять, если удаляется пользователь

Исправлено

2023-07-03 09:15 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        });
> Да, примерно так. Добавляешь `refreshToken.HasIndex(r => r.Token).IsUnique();`, потом добавляешь новую миграцию `dotnet ef migrations add AddRefreshTokenIndexOnToken` и потом можно БД обновить.
> 
> После этого в БД создастся новый индекс и запрос по этому полю будет сильно быстрее выполняться

Исправлено

2023-07-03 09:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Options/RefreshTokenOptions.cs
> +    public int HashLengthInBytes { get; set; }
> Hash ты в логике нигде не используешь. Поэтому нужно переименовать свойство

Исправлено

2023-07-03 09:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +    private string GenerateAccesToken(User user)
> Опечатка в `Access`

Исправлено

2023-07-03 09:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var NotRevokeRefreshToken = refreshTokens.FirstOrDefault(t => !t.Revoke);
> Нужно с маленькой буквы

Исправлено

2023-07-03 09:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
> Пробелы

Исправлено

2023-07-03 09:17 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                await transaction.RollbackAsync(cancellationToken);
> Нужно после этого еще `throw` добавить, чтобы исключение дальше летело. Иначе ты в БД ничего не сохранил, а токены вернул клиенту и он думает, что они валидные

Исправлено

2023-07-03 09:18 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Requests/GetNewTokens.cs
> +                    .FirstOrDefaultAsync(cancellationToken);
> `SingleOrDefaultAsync`. У тебя по семантике может быть 0 или 1 такой токен

Исправлено

2023-07-03 09:18 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Requests/Controllers/AuthController.cs
> +        var refreshToken = Request.Cookies["refreshToken"];
> Строка "refreshToken" в двух местах используется. Нужно вынести в константу

Исрпавлено

2023-07-03 09:18 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                var overdueTokens = refreshTokens.Where(x => x.ExpiryDate<=DateTime.Now.ToUniversalTime()).ToArray();
> Да, правильно. В токен ты просаживаешь время, после которого его можно удалять.
> 
> > А если же увеличить свойство ExpiryDate до 168:00:00 то высока вероятность, что токен, могу украсть.
> 
> Правильно. Поэтому нужно два отдельных свойства:
> 
> * время жизни токена
> * время, после которого токен можно удалить

Исправлено

2023-07-03 09:34 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Options/RefreshTokenOptions.cs
> +    public TimeSpan RefreshTokenExpirationPeriod { get; set; }
Непонятно, чем отличается от предыдущего свойства. Нужно поменять имя согласно семантике

2023-07-03 09:34 UTC, mitro commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        modelBuilder.Entity<RefreshToken>(refreshToken =>
Не все свойства класса тут замаплены

2023-07-03 13:04 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Features/Auth/Options/RefreshTokenOptions.cs
> +    public TimeSpan RefreshTokenExpirationPeriod { get; set; }
> Непонятно, чем отличается от предыдущего свойства. Нужно поменять имя согласно семантике

Исправлено

2023-07-03 13:04 UTC, MukanMasud1992 commented on CryptoBank.WebApi/Database/ApplicationDbContext.cs
> +        modelBuilder.Entity<RefreshToken>(refreshToken =>
> Не все свойства класса тут замаплены

Исправлено

2023-07-03 13:10 UTC, mitro approved these changes

2023-07-03 13:19 UTC, merged