Add new features/error-handler
MasDev-12/CryptoBank.WebApi pull request #7
Opened 2023-07-03 15:26 UTC by MukanMasud1992

Add new features/error-handler please check

2023-07-04 06:31 UTC, mitro requested changes

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Program.cs
> +app.MapPromlebDetails();
Очепятка)

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Errors/Extensions/ApplicationBuilderExtensions.cs
> +                            var validationProblemDetails = new ProblemDetails
Нужно вынести повторяющийся код во всех ветках в отдельный метод

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Errors/Extensions/ApplicationBuilderExtensions.cs
> +internal record ErrorData(
Эта запись вроде не используется. Я её делал просто для демонстрации. Удали её и переименуй `ErrorDataWithCode` просто в `ErrorData`

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Errors/AccountLogicConflictErrors.cs
> +    private const string Prefix = "Account_logic_conflict";
`Account` лучше с маленькой буквы. И в конце нужно добавить `_`, иначе после склейки не будет разделителя.

И во всех классах с ошибками перепроверь и поправь, если такие же проблемы

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Errors/AccountValidationErrors.cs
> +    public const string AccountExist = Prefix + "account_exist";
`Exists` более правильно с точки зрения английского языка. И перепроверь все остальные классы. Там тоже есть эта ошибка, нужно поправить

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Errors/UserLogicConflictErrors.cs
> +    public static string RoleAlreadyUse = Prefix + "role_already_added_previous";
`RoleAlreadyUsed` и `role_already_used`

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Requests/GetOwnAccounts.cs
>                      var ExistUser = await applicationDbContext.Users.AnyAsync(user => user.Id == x);
Переменная должна быть с маленькой буквы

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Errors/AuthLogicConflictErrors.cs
> +    public static string AuthInvalidCredentials = Prefix + "Invalid credentials";
В качестве разделителей нужно использовать `_`, а не пробелы. И всё с маленькой буквы должно быть

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +                 }).WithErrorCode(EmailExistOrInvalid);
Тут же наоборот? Нужно чтобы код ошибки говорил о том, что имейл не существует или пароль неверен.

И вообще тут наверно эта проверка не нужна? Ты в хендлере пытаешься найти пользователя по имейлу и как раз кидаешь нужную ошибку, если он не найден

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Auth/Services/TokenGenerateService.cs
> +                throw new LogicConflictException("Refresh token error", AuthLogicConflictErrors.RefreshTokenError);
Тут должна быть внутренная ошибка `InternalErrorException`. Исключение может быть сгенерировано только если у нас перестала работать БД, а это уже поломка сервера, а не логическая ошибка

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +                }).WithErrorCode(EmailExistOrInvalid);
А что значит `OrInvalid`?

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/UpdateUserRole.cs
> +                throw new LogicConflictException("Role already use", RoleAlreadyUse);
Тут не ошибка валидации? Клиент прислал неверную роль - проблема на его стороне

2023-07-04 06:31 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/UpdateUserRole.cs
> +              }).WithErrorCode(EmailExistOrInvalid);
Тут же наоборот? `EmailNotExists` нужно. И что значит `OrInvalid`?

2023-07-10 01:56 UTC, mitro commented on CryptoBank.WebApi/Program.cs
> +app.MapPromlebDetails();
Всё равно неправильно

2023-07-10 01:58 UTC, mitro commented on CryptoBank.WebApi/Features/Accounts/Errors/AccountValidationErrors.cs
> +    public const string AccountExist = Prefix + "account_exist";
Имена констант не поправил

2023-07-10 01:59 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Errors/UserLogicConflictErrors.cs
> +    public static string RoleAlreadyUse = Prefix + "role_already_added_previous";
Имя константы не поправил

2023-07-10 02:04 UTC, mitro commented on CryptoBank.WebApi/Features/Users/Requests/UpdateUserRole.cs
> +                throw new LogicConflictException("Role already use", RoleAlreadyUse);
Не поправил

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
>              if (user == null)
Есть тут один момент, я проверяю user на null, по сути валидация, ранее я его в валидаторе проверял, я думаю, что эта проверка не нужна, но все таки, почему его оставил не помню, может есть мнение у Вас?

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Program.cs
> +app.MapPromlebDetails();
> Очепятка)

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Errors/Extensions/ApplicationBuilderExtensions.cs
> +                            var validationProblemDetails = new ProblemDetails
> Нужно вынести повторяющийся код во всех ветках в отдельный метод

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Accounts/Errors/AccountLogicConflictErrors.cs
> +    private const string Prefix = "Account_logic_conflict";
> Collaborator

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Accounts/Errors/AccountValidationErrors.cs
> +    public const string AccountExist = Prefix + "account_exist";
> `Exists` более правильно с точки зрения английского языка. И перепроверь все остальные классы. Там тоже есть эта ошибка, нужно поправить

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Users/Errors/UserLogicConflictErrors.cs
> +    public static string RoleAlreadyUse = Prefix + "role_already_added_previous";
> `RoleAlreadyUsed` и `role_already_used`

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Accounts/Requests/GetOwnAccounts.cs
>                      var ExistUser = await applicationDbContext.Users.AnyAsync(user => user.Id == x);
> Переменная должна быть с маленькой буквы

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Auth/Errors/AuthLogicConflictErrors.cs
> +    public static string AuthInvalidCredentials = Prefix + "Invalid credentials";
> В качестве разделителей нужно использовать `_`, а не пробелы. И всё с маленькой буквы должно быть

Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Auth/Requests/LoginUser.cs
> +                 }).WithErrorCode(EmailExistOrInvalid);
> Тут же наоборот? Нужно чтобы код ошибки говорил о том, что имейл не существует или пароль неверен.
> 
> И вообще тут наверно эта проверка не нужна? Ты в хендлере пытаешься найти пользователя по имейлу и как раз кидаешь нужную ошибку, если он не найден

ДА верно, она тут не нужна, логично. Исправлено

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Users/Requests/RegisterUser.cs
> +                }).WithErrorCode(EmailExistOrInvalid);
> А что значит `OrInvalid`?

Была мысли, что при логировании использовать эту ошибку, счс осознаю, что это только регистрация, по этому invalid не нужно

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Users/Requests/UpdateUserRole.cs
> +                throw new LogicConflictException("Role already use", RoleAlreadyUse);
> Collaborator

Ошибка валидации уже прошла, "  RuleFor(x => x.UpdateRole)
             .Cascade(CascadeMode.Stop)
             .IsInEnum()
             .WithErrorCode(InvalidRole);" тут ловит.
Здесь же ошибка происходит в случае, если роль уже есть у пользователя, и выдает юшибку, зачем плодить в БД записи, одних и тех же ролей

2023-07-10 03:31 UTC, MasDev-12 commented on CryptoBank.WebApi/Features/Users/Requests/UpdateUserRole.cs
> +              }).WithErrorCode(EmailExistOrInvalid);
> Тут же наоборот? `EmailNotExists` нужно. И что значит `OrInvalid`?

Если, пользователя в БД нету, кому роль присвоить? Тут выдаст пользователя не существует

2023-07-10 03:34 UTC, mitro approved these changes

2023-07-10 04:16 UTC, merged